import { Hanken_Grotesk } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const HankenSans = Hanken_Grotesk({
  variable: "--font-hanken-sans",
  subsets: ["latin"],
});

// const Molend = localFont({
//   src: "./public/fonts/molend-v4.tff",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${HankenSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
